# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hao Zhang
name: Hao Zhang(张浩)
position: master's student from Tsinghua-RWTH Aachen Double Master's Degree Program 
email: hao.zhang270199@gmail.com
linkedin: hao-zhang-0435b924a
description: >-
  I am a master's student from [Tsinghua](https://www.tsinghua.edu.cn/en/)-[RWTH Aachen](https://www.rwth-aachen.de/go/id/a/?lidx=1) Double Master's Degree Program advised by [Prof. Pingfa Feng](https://www.me.tsinghua.edu.cn/en/info/1083/1249.htm) and [Prof. Long Zeng](https://www.sigs.tsinghua.edu.cn/cl_en/main.htm). 
  My research interests lie in computer vision and robotics.
  

  Previously, I was a research assistant at [Max Planck Institute for Intelligent Systems](https://is.mpg.de/) working with [Dr. Yandong Wen](https://is.mpg.de/person/ydwen), [Yao Feng](https://is.mpg.de/person/yfeng), and [Prof. Michael Black](https://is.mpg.de/person/black) applying the AIGC in 3D avatars generation.
  
  Before that, I was a research assistant at [TAMS, University of Hamburg](https://tams.informatik.uni-hamburg.de/) working with [Dr. Hongzhuo Liang](https://tams.informatik.uni-hamburg.de/people/liang/) and [Prof. Jianwei Zhang](https://tams.informatik.uni-hamburg.de/people/zhang/) 

baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://keunhong.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: KeunhongP
github_username: HaoZhang990127
google_scholar: Hao Zhang
# google_analytics: G-MFWSBLRKG0

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
